### ISSUE TITLE
Post to Slack when new content is added

### ISSUE THREAD

**Issue by gunsch** [adhocteam/nytimes-library#14]
User story: people don't know when new content is added, which limits that new content's usefulness.

Hypothesis: notifying Slack when new docs are added will help create awareness of new, useful content.

When new files are detected in the Content Library Shared Drive, post to the `#content-writing` Slack channel about it.

**Comment by zenkimoto** [comment]
Just wondering how would the application know if there's new content?  Somehow we need to store the before and after.  Or maybe check creation date since the last check?  We would need to store that date somewhere.  Just thinking ideas.

**Comment by gunsch** [comment]
Hmm! Two ideas that come to mind:

(1) A daily job that just posts everything added in the last day (though, we'd probably have to start by figuring out how to configure a cron / daily job in this app, or split it across the people app)

(2) wherever the sync / ingest is in this codebase. somewhere in here it syncs with Google Drive, then adds records of new files into the Datastore instance. when that happens, can we also add a hook like posting to Slack?

**Comment by timwright12** [comment]
Are we able to utilize some thing like [If This Then That](https://ifttt.com/google_drive) for this purpose? It seems like there are some recipes on there for connecting Drive and Slack.

**Comment by gunsch** [comment]
We used to do things like that in Zapier, but generally these services get into payment and licensing issues --- not to mention some added complexity of the implementation sprawling outside the existing infrastructure. I'd rather not go that route

**Comment by wolvgrad98** [comment]
The content library has fallen out of use and `#content-writing` Slack channel is archived.
