### ISSUE TITLE
Create continuous delivery pipeline for dev and production environments

### ISSUE THREAD

**Issue by ahinh43** [adhocteam/nytimes-library#38]
To facilitate safe and fast deployments, we'll want a CD pipeline created to deploy our changes in the main branch to our dev and production environments

**Question:** If our library app is internal to Ad Hoc only, is there any opposition to practice deploying changes to production as soon as they make it to the main branch?

**Comment by gunsch** [comment]
I'll approve the idea to directly deploy changes to production once merged to `main`. (personally that's my preference)

**Comment by ahinh43** [comment]
With #56 for prod, #45, #48 and #49 completed for dev, this can be closed as done
