### ISSUE TITLE
Content Library: Upgrade Node version

### ISSUE THREAD

**Issue by gunsch** [adhocteam/nytimes-library#41]
NPM no longer works with Node 10, but this application is currently node10 based.

Do a Node upgrade, ideally jumping up to Node 16 (current LTS) and make sure the app still works.

This also needs to show up in `app.yaml`, changing the GAE runtime to `nodejs16` (https://cloud.google.com/appengine/docs/standard/nodejs/runtime)

**Comment by zenkimoto** [comment]
Just FYI, nodejs 16 EOL date just moved up to 9/11/23.

https://nodejs.org/en/blog/announcements/nodejs16-eol/

**Comment by ahinh43** [comment]
No terraform code changes are needed, [this is the only area I had in mind for the version upgrade](https://github.com/adhocteam/nytimes-library/blob/e8b46dc145ed1cf349f120cd1c1895551b2a4510/.github/workflows/cicd-cloud-dev.yml#L16). We'll want to sync that up to node 16 so our development builds and CI builds are the same

After that then it all LGTM
