### ISSUE TITLE
Lock down content-library-dev to adhocteam.us addresses

### ISSUE THREAD

**Issue by gunsch** [adhocteam/nytimes-library#58]
Right now it's viewable by anyone, but it's using the same official Drive. It should stay restricted to adhocteam.us addresses.

Should just be a matter of updating some of the env variables.

**Comment by zenkimoto** [comment]
This is only in dev.  We just need to remove the value in `NODE_ENV` and change it to something other than `development` since `development` is really meant for local development.

**Comment by zenkimoto** [comment]
Locked down!  I verified with my personal account on both prod/dev.  Though, it really only affected dev.

**Comment by zenkimoto** [comment]
Oh yeah, I should have read more carefully on the title regarding dev...
