### ISSUE TITLE
Build terraform config for this application

### ISSUE THREAD

**Issue by gunsch** [adhocteam/nytimes-library#6]
Probably in the `infrastructure` repo?

We don't have any GCP terraform config yet though, so this might take some more involved work.

**Comment by mariosmith90** [comment]
@gunsch I have started a terraform config for this application. Perhaps you can create a new issue, one broader in scope for any enhancements, tests, and additional environments needed for my base config.

**Comment by mariosmith90** [comment]
> Probably in the `infrastructure` repo?
> 
> We don't have any GCP terraform config yet though, so this might take some more involved work.

I have a basic config up locally on my machine. It works but is not ready for 'primetime' and there's some formatting to be done before it has reached that point.

**Comment by ahinh43** [comment]
Terraform IaC was written in this [PR](https://github.com/adhocteam/nytimes-library/pull/22), a follow up ticket will be created to wire up the production environment
