### ISSUE TITLE
Auto-deploy Content Libray application from GitHub Actions

### ISSUE THREAD

**Issue by gunsch** [adhocteam/nytimes-library#7]
Currently deployment is happening from... well, my machine. The `.env` file isn't checked in and has some secrets in it.

This will take some GitHub Actions work, and probably baking in the secrets somewhere --- either in the GCP project config, or behind the scenes in the GHA.

**Comment by gunsch** [comment]
https://github.com/google-github-actions/deploy-appengine looks promising

@ahinh43 curious for your thoughts here on
- setting up a proper terraform config for this app / how much lift that would take? vs just
- using a GitHub Actions flow to do a gcloud deploy (not really IaC)

**Comment by mariosmith90** [comment]
@gunsch The dotenv/config has a number of hooks within the application which is causing issues when the app deploys in CICD as dotenv/config is not intended outside of local dev. As you mentioned some work does need to be done. I was thinking of a number of different ways to 'skin this cat' one of which was passing the variables through docker using GHA secrets.

**Comment by gunsch** [comment]
Hmm I'm open to any of the above! 

When you say "pass the variables through docker using GHA secrets", does that imply coding the secrets into the Docker image at build-time?

I wonder if another approach could (or should) be passing them in through GCP as run-time secrets injected into the env --- so the secrets aren't baked into the image

**Comment by gunsch** [comment]
duplicate of #38
