### ISSUE TITLE
Content Library: many searches causing 500s

### ISSUE THREAD

**Issue by gunsch** [adhocteam/nytimes-library#72]
i.e.
https://content-library.adhoc.pizza/search?q=accessibility&types=

triggers a 500 :(

**Comment by timwright12** [comment]
Not sure hoe helpful this is for debugging, but in testing this a little further and there are some substrings in "accessibility" that throw the 500 error as well:

**Fail (500 error):**

- a
- acce
- acces
- access
- accessib
- accessibility

**Pass (returns):**

- ac
- acc
- accessi
- accessibi
- accessibil
- accessibili
- accessibilit

**Single letters that throw a 500 error:**

- a
- i
- t

**Comment by timwright12** [comment]
**Error from the log:**

```
    error: {
      errors: [
        {
          domain: 'global',
          reason: 'invalid',
          message: 'Invalid Value',
          locationType: 'parameter',
          location: 'pageToken'
        }
      ],
      code: 400,
      message: 'Invalid Value'
    }
```

**Comment by bkjohnson** [comment]
So far it seems like what's used in a deployment doesn't match code that's used when running things locally. I removed this entire chunk from the `handlePage` function which handles when the `/search` page is hit:

https://github.com/adhocteam/nytimes-library/blob/b4cb37120482ca26e1a785a2429bcfb6c362bfcb/custom/routes/pages.js#L33-L62

Locally I end up with something like this (notice the "hello" in the query params):

![The server running locally with the `/search` page open in the browser. The query string in the URL shows that "hello" was the search term, but the page shows that an empty string was used.](https://user-images.githubusercontent.com/2008881/208167327-c9cf6182-b02e-495b-977f-932890011b06.png)


But when I deploy the code to a dev environment using gcloud, nothing changes. I still get the 500 error on search terms that I would get it on previously, and I still get search results on terms that worked previously.

**Comment by timwright12** [comment]
@bkjohnson maybe some heavy caching that needs to be cleared out?
